Repository xnd-project/rbc, pull requests merged in 2020-11, with the labels that each got.

#210 Enable test_black_scholes_udtf
  rbc/tests/test_omnisci_black_scholes.py
Labels: code quality, omniscidb

#212 Tests for aggregates on UDTF output columns
  rbc/omniscidb.py
  rbc/tests/test_omnisci_column_basic.py
Labels: enhancement, omniscidb

#214 Fix issue 197
  rbc/omnisci_backend/numpy_funcs.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_column_basic.py
Labels: bug

#219 Make TargetInfo globally available
  rbc/irtools.py
  rbc/omnisci_backend/numpy_funcs.py
  rbc/omnisci_backend/omnisci_array.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/targetinfo.py
  rbc/tests/test_omnisci_array_functions.py
  rbc/tests/test_remotejit.py
  rbc/tests/test_typesystem.py
  rbc/typesystem.py
Labels: enhancement
