Repository xnd-project/rbc, pull requests merged in 2020-12, with the labels that each got.

#228 Introduce TargetInfo.check_enabled and RemoteJIT.preprocess_callable
  rbc/remotejit.py
  rbc/targetinfo.py
Labels: enhancement

#227 Introduce TargetInfo.llvm_version property.
  rbc/irtools.py
  rbc/omniscidb.py
  rbc/targetinfo.py
Labels: enhancement

#225 Support TEXT ENCODING NONE as Bytes
  rbc/irtools.py
  rbc/omnisci_backend/__init__.py
  rbc/omnisci_backend/omnisci_array.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_bytes.py
  rbc/omnisci_backend/omnisci_pipeline.py
  rbc/omniscidb.py
  rbc/targetinfo.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_text.py
Labels: enhancement, omniscidb

#229 Implement tests for omniscdb-internal PR 5026
  rbc/tests/__init__.py
  rbc/tests/test_omnisci.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_device_selection.py
  utils/scan_for_extern_C.py
Labels: enhancement, omniscidb

#231 Add test for support columns with different sizes as inputs to UDTFs
  rbc/tests/test_omnisci_column_basic.py
Labels: enhancement, omniscidb

#238 Tests for omniscidb-internal PR 5134 - fix multiple cursor argument support for UDTFs
  rbc/tests/__init__.py
  rbc/tests/test_omnisci_column_arguments.py
  rbc/tests/test_omnisci_column_basic.py
Labels: omniscidb
