Repository xnd-project/rbc, pull requests merged in 2020-08, with the labels that each got.

#139 Backport to numba 0.48
  rbc/irtools.py
Labels: bug

#119 Fix returning boolean array
  rbc/irtools.py
  rbc/omnisci_backend/__init__.py
  rbc/omnisci_backend/numpy_funcs.py
  rbc/omnisci_backend/numpy_ufuncs.py
  rbc/omniscidb.py
  rbc/tests/test_omnisci.py
  rbc/tests/test_omnisci_array_math.py
  rbc/typesystem.py
Labels: bug

#137 Enables tests that were previously failing
  rbc/tests/test_omnisci_array_functions.py
  rbc/tests/test_omnisci_array_math.py
  rbc/tests/test_omnisci_array_methods.py
  rbc/tests/test_omnisci_array_operators.py
Labels: bug

#145 Eliminate bool_is_int8 from mangling algorithm
  rbc/irtools.py
  rbc/omniscidb.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_array_methods.py
  rbc/tests/test_omnisci_array_operators.py
  rbc/typesystem.py
Labels: code quality

#116 UDTF Column argument support
  rbc/omnisci_backend/__init__.py
  rbc/omnisci_backend/omnisci_array.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omnisci_backend/python_operators.py
  rbc/omniscidb.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_udtf.py
  rbc/typesystem.py
Labels: enhancement

#144 enable boolean8 tests and call functions from the "omni" pkg
  rbc/omnisci_backend/numpy_ufuncs.py
  rbc/tests/test_omnisci_array_math.py
  rbc/tests/test_omnisci_math.py
Labels: enhancement

#153 Enable issue 148 tests
  rbc/omnisci_backend/numpy_ufuncs.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_math.py
Labels: code quality

#154 Add np.signbit, np.ldexp
  rbc/npy_mathimpl.py
  rbc/omnisci_backend/numpy_ufuncs.py
  rbc/tests/test_numpy_rjit.py
  rbc/tests/test_omnisci_array_math.py
  rbc/tests/test_omnisci_math.py
Labels: enhancement

#157 add tests for python math.* functions
  rbc/irtools.py
  rbc/npy_mathimpl.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_math.py
Labels: enhancement

#163 Enable array support in load_table_columns
  rbc/extension_functions.thrift
  rbc/omniscidb.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_column_basic.py
Labels: enhancement, upstream

#161 Add black-scholes test
  rbc/tests/data_black_scholes.csv
  rbc/tests/test_omnisci_black_scholes.py
Labels: enhancement

#164 Notebook: use UDTF to normalize a table column
  notebooks/rbc-omnisci-udtf-normalize.ipynb
Labels: notebook

#172 Expose RemoteOmnisci
  rbc/__init__.py
Labels: bug, enhancement
