Repository xnd-project/rbc, pull requests merged in 2021-01, with the labels that each got.

#243 Replace miniconda -> minimamba on circleci
  .circleci/config.yml
Labels: enhancement

#241 Implement templates support and make custom type a fundamental type of RBC typesystem
  rbc/omnisci_backend/omnisci_array.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_bytes.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/targetinfo.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_remotejit.py
  rbc/tests/test_typesystem.py
  rbc/typesystem.py
Labels: enhancement

#239 Support Column is_null (replaces PR #230)
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omniscidb.py
  rbc/targetinfo.py
  rbc/tests/__init__.py
  rbc/tests/test_omnisci.py
  rbc/tests/test_omnisci_column_null.py
  rbc/typesystem.py
Labels: omniscidb

#236 Restore allocate_varlen_buffer
  rbc/irtools.py
  rbc/omnisci_backend/omnisci_buffer.py
Labels: bug, enhancement, omniscidb

#253 Ignore cpu features due to llvm version mismatch
  rbc/irtools.py
Labels: enhancement, omniscidb

#260 Fix setting array null values to None. Add tests to test tables. Support NULLs in table_load_columnar.
  rbc/extension_functions.thrift
  rbc/omniscidb.py
  rbc/tests/__init__.py
  rbc/tests/test_omnisci_testing.py
Labels: bug

#244 null support in UDF
  .travis.yml
  rbc/omnisci_backend/numpy_funcs.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/tests/__init__.py
  rbc/tests/test_omnisci_array_null.py
Labels: enhancement, omniscidb

#257 test with gh-actions
  .appveyor.yml
  .circleci/config.yml
  .github/workflows/rbc_test.yml
Labels: enhancement

#269 Support C function prototypes. Add Type.name property to function types
  rbc/omniscidb.py
  rbc/tests/test_typesystem.py
  rbc/typesystem.py
Labels: code quality, enhancement
