Repository xnd-project/rbc, pull requests merged in 2021-12, with the labels that each got.

#385 Add omniscidb v5.9 to our CI
  .github/workflows/rbc_test.yml
  rbc/tests/__init__.py
Labels: enhancement, omniscidb

#386 Drop support for omniscidb v5.(2/3/4/5)
  notebooks/rbc-omnisci-udf.ipynb
  rbc/omniscidb.py
  rbc/tests/test_omnisci.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_array_functions.py
  rbc/tests/test_omnisci_array_methods.py
  rbc/tests/test_omnisci_array_null.py
  rbc/tests/test_omnisci_array_operators.py
  rbc/tests/test_omnisci_black_scholes.py
  rbc/tests/test_omnisci_column_arguments.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_column_default.py
  rbc/tests/test_omnisci_column_list.py
  rbc/tests/test_omnisci_column_null.py
  rbc/tests/test_omnisci_device_selection.py
  rbc/tests/test_omnisci_math.py
  rbc/tests/test_omnisci_text.py
  rbc/tests/test_omnisci_treelite.py
  rbc/tests/test_omnisci_udtf.py
Labels: deprecation

#389 Add test for issues #77 and #235
  rbc/omniscidb.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_udtf.py
Labels: tests

#388 Change the return value if the array is empty for `max`
  rbc/omnisci_backend/numpy_funcs.py
  rbc/tests/test_omnisci_array_methods.py
Labels: enhancement

#380 Enable the Array API even without omnisci, and fix/detect memory leaks
  .conda/environment.yml
  .conda/meta.yaml
  .github/workflows/rbc_test.yml
  doc/conf.py
  rbc/libfuncs.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omniscidb.py
  rbc/rbclib/__init__.py
  rbc/rbclib/_rbclib.c
  rbc/rbclib/_rbclib.h
  rbc/rbclib/_rbclib_build.py
  rbc/rbclib/errors.py
  rbc/rbclib/intrinsic.py
  rbc/rbclib/tracing_allocator.py
  rbc/remotejit.py
  rbc/stdlib/__init__.py
  rbc/stdlib/array_api.py
  rbc/targetinfo.py
  rbc/tests/stdlib/__init__.py
  rbc/tests/stdlib/test_array_api.py
  rbc/tests/test_rbclib.py
  rbc/tests/test_targetinfo.py
  requirements.txt
  setup.py
Labels: bug, enhancement
