Repository xnd-project/rbc, pull requests merged in 2021-05, with the labels that each got.

#313 Add tests for sizer with default value - omniscidb-internal PR 5403
  rbc/tests/test_omnisci_column_arguments.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_column_default.py
Labels: omniscidb, tests

#309 Fix readthedocs build
  .gitignore
  .readthedocs.yml
  doc/_ext/numbadoc.py
  doc/_static/copybutton.js
  doc/_static/style.css
  doc/_templates/autosummary/base.rst
  doc/_templates/autosummary/class.rst
  doc/_templates/autosummary/module.rst
  doc/_templates/layout.html
  doc/api.rst
  doc/conf.py
  doc/design.rst
  doc/index.rst
  doc/make.bat
  doc/omnisci/array.rst
  doc/omnisci/bytes.rst
  doc/omnisci/column.rst
  doc/omnisci/columnlist.rst
  doc/omnisci/outputcolumn.rst
  doc/rbc/api.rst
  doc/rbc/index.rst
  doc/rbc/numpy_support.rst
  doc/releases.rst
  doc/releases/index.rst
  rbc/errors.py
  rbc/external.py
  rbc/externals/__init__.py
  rbc/externals/cmath.py
  rbc/externals/libdevice.py
  rbc/externals/macros.py
  rbc/externals/stdio.py
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/targetinfo.py
  rbc/tests/__init__.py
  rbc/typesystem.py
  rbc/utils.py
  test_requirements.txt
Labels: documentation

#330 Fix test_omnisci_array_null tests
  rbc/tests/__init__.py
  rbc/tests/test_omnisci_array_null.py
  rbc/tests/test_omnisci_testing.py
  rbc/utils.py
Labels: bug

#331 Fix require_version date in test_omnisci_column_arguments
  rbc/tests/test_omnisci_column_arguments.py
Labels: bug

#335 Various test fixes
  rbc/externals/__init__.py
  rbc/tests/test_externals_libdevice.py
  rbc/tests/test_omnisci_column_arguments.py
  rbc/tests/test_omnisci_column_basic.py
  rbc/tests/test_omnisci_column_list.py
Labels: bug, tests

#338 Disable caching for logaddexp/logaddexp2
  rbc/irtools.py
  rbc/omnisci_backend/npyimpl.py
Labels: bug

#339 Enable gpu trigonometric tests
  rbc/tests/test_externals_libdevice.py
  rbc/tests/test_omnisci_math.py
Labels: omniscidb, tests
