Repository xnd-project/rbc, pull requests merged in 2021-02, with the labels that each got.

#268 Add command to declare external functions
  notebooks/rbc-omnisci-external-fns.ipynb
  rbc/external.py
  rbc/libfuncs.py
  rbc/tests/test_external.py
Labels: enhancement

#274 Introduce dummy target info
  rbc/targetinfo.py
  rbc/tests/test_typesystem.py
  rbc/typesystem.py
Labels: enhancement

#273 Change external behaviour to work with hardware-specific types
  rbc/external.py
  rbc/tests/test_external.py
Labels: enhancement

#267 Introduce ccompiler, Array.ptr and a prototype of treelite prediction model as an UDF
  .conda/environment.yml
  .conda/meta.yaml
  .github/workflows/rbc_test.yml
  .travis.yml
  rbc/ctools.py
  rbc/irtools.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omniscidb.py
  rbc/tests/__init__.py
  rbc/tests/boston_house_prices.csv
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_treelite.py
  setup.py
Labels: demo, enhancement

#279 Replace travis ci by github actions
  .github/workflows/rbc_test.yml
  .travis.yml
  docker-compose.yml
Labels: enhancement

#275 External with device parameter
  rbc/external.py
  rbc/externals/math.py
  rbc/irtools.py
  rbc/omnisci_backend/omnisci_pipeline.py
  rbc/omniscidb.py
  rbc/tests/test_external.py
  rbc/tests/test_omnisci_math.py
  rbc/utils.py
  setup.cfg
Labels: bug, enhancement

#288 Fix gh-action when installing omniscidb from conda-forge
  .github/workflows/rbc_test.yml
Labels: enhancement

#287 Add a CHANGELOG file to RBC
  .github/workflows/changelog.yml
  .github/workflows/label_check.yml
  changelog_config.json
Labels: enhancement
