Repository xnd-project/rbc, pull requests merged in 2021-03, with the labels that each got.

#292 Support remote access and conversion of pointer values of scalar, struct, and pointer types
  rbc/external.py
  rbc/externals/macros.py
  rbc/irtools.py
  rbc/omnisci_backend/omnisci_array.py
  rbc/omnisci_backend/omnisci_bytes.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/remotejit.thrift
  rbc/structure_type.py
  rbc/targetinfo.py
  rbc/tests/test_remotejit.py
  rbc/tests/test_typesystem.py
  rbc/tests/test_utils.py
  rbc/thrift/dispatcher.py
  rbc/thrift/server.py
  rbc/thrift/types.py
  rbc/typesystem.py
  rbc/utils.py
Labels: enhancement

#286 Add cmath and libdevice external functions and gpu bindings to cmath and numpy
  rbc/external.py
  rbc/externals/__init__.py
  rbc/externals/cmath.py
  rbc/externals/libdevice.py
  rbc/externals/stdio.py
  rbc/irtools.py
  rbc/omnisci_backend/__init__.py
  rbc/omnisci_backend/cuda_npyimpl.py
  rbc/omnisci_backend/mathimpl.py
  rbc/omnisci_backend/npy_mathimpl.py
  rbc/omnisci_backend/npyimpl.py
  rbc/omnisci_backend/numpy_funcs.py
  rbc/omniscidb.py
  rbc/targetinfo.py
  rbc/tests/test_external.py
  rbc/tests/test_externals_cmath.py
  rbc/tests/test_externals_libdevice.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_math.py
  setup.cfg
Labels: enhancement

#301 Test cmath functions using RemoteJIT
  .github/workflows/rbc_test.yml
  rbc/external.py
  rbc/externals/cmath.py
  rbc/tests/test_externals_cmath.py
Labels: tests

#308 Deprecate numba 0.49 and add python 3.9 support
  .github/workflows/pypi.yml
  .github/workflows/rbc_test.yml
  rbc/errors.py
  rbc/externals/__init__.py
  rbc/externals/stdio.py
  rbc/irtools.py
  rbc/omnisci_backend/npyimpl.py
  rbc/omnisci_backend/numpy_funcs.py
  rbc/omnisci_backend/numpy_ufuncs.py
  rbc/omnisci_backend/omnisci_array.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_bytes.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omnisci_backend/omnisci_pipeline.py
  rbc/omnisci_backend/python_operators.py
  rbc/tests/test_omnisci_array_functions.py
  rbc/typesystem.py
  utils/remotenumba.py
Labels: code quality, deprecation

#306 Implement ColumnList support for runtime UDTFs
  rbc/extension_functions.thrift
  rbc/omnisci_backend/__init__.py
  rbc/omnisci_backend/column_list.py
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omniscidb.py
  rbc/structure_type.py
  rbc/tests/test_omnisci_column_arguments.py
  rbc/tests/test_omnisci_column_list.py
  rbc/typesystem.py
Labels: enhancement, omniscidb
