Repository xnd-project/rbc, pull requests merged in 2022-04, with the labels that each got.

#481 Remove pytest.mark.skip from test
  rbc/tests/heavydb/test_array_api_unsupported.py
Labels: tests

#478 Restore remotejit section
  .github/workflows/rbc_test.yml
Labels: tests

#480 Sets Numba error mode to new style and implement auto cast on setitem
  rbc/__init__.py
  rbc/heavydb_backend/buffer.py
  rbc/heavydb_backend/table_function_manager.py
  rbc/heavydb_backend/text_encoding_none.py
  rbc/tests/test_remotejit.py
Labels: enhancement

#479 Rename heavydb_backend -> heavydb
  rbc/heavyai/text_encoding_dict.py
  rbc/heavyai/text_encoding_none.py
  rbc/heavydb/__init__.py
  rbc/heavydb/array.py
  rbc/heavydb/buffer.py
  rbc/heavydb/column.py
  rbc/heavydb/column_list.py
  rbc/heavydb/mathimpl.py
  rbc/heavydb/metatype.py
  rbc/heavydb/npyimpl.py
  rbc/heavydb/pipeline.py
  rbc/heavydb/python_operators.py
  rbc/heavydb/remoteheavydb.py
  rbc/heavydb/table_function_manager.py
  rbc/heavydb/text_encoding_dict.py
  rbc/heavydb/text_encoding_none.py
  rbc/remotejit.py
  rbc/tests/heavydb/test_array_math.py
  rbc/tests/heavydb/test_heavydb.py
  rbc/tests/heavydb/test_missing_symbol.py
Labels: code quality

#483 cast boolean literal to Boolean8
  rbc/tests/heavydb/test_array.py
  rbc/typesystem.py
Labels: enhancement

#484 Pure python release
  .github/workflows/pypi.yml
Labels: Skip-Changelog, skip-tests
