Repository xnd-project/rbc, pull requests merged in 2022-03, with the labels that each got.

#447 Support HeavyDB
  rbc/extension_functions.thrift
  rbc/omniscidb.py
  rbc/tests/test_omnisci.py
Labels: enhancement

#455 Bump heavydb to 6.1.0
  rbc/tests/__init__.py
Labels: enhancement

#452 Derive dtype from fill_value
  rbc/__init__.py
  rbc/errors.py
  rbc/stdlib/creation_functions.py
  rbc/tests/heavyai/test_array.py
  rbc/tests/heavyai/test_array_functions.py
  rbc/tests/heavyai/test_math.py
Labels: enhancement

#458 Remove AutoFreeBuffers pass
  .conda/environment.yml
  .conda/meta.yaml
  .github/workflows/pypi.yml
  .github/workflows/rbc_test.yml
  rbc/heavyai/__init__.py
  rbc/heavyai/buffer.py
  rbc/heavyai/pipeline.py
  rbc/heavydb.py
  rbc/irtools.py
  rbc/libfuncs.py
  rbc/rbclib/__init__.py
  rbc/rbclib/_rbclib.c
  rbc/rbclib/_rbclib.h
  rbc/rbclib/_rbclib_build.py
  rbc/rbclib/errors.py
  rbc/rbclib/intrinsic.py
  rbc/rbclib/tracing_allocator.py
  rbc/remotejit.py
  rbc/stdlib/statistical_functions.py
  rbc/targetinfo.py
  rbc/tests/stdlib/__init__.py
  rbc/tests/stdlib/test_array_api.py
  rbc/tests/test_rbclib.py
  rbc/tests/test_targetinfo.py
  requirements.txt
  setup.py
  test_requirements.txt
Labels: enhancement

#464 Introduce RemoteHeavyDB.reconnect. Test UDF registration by non-admin users.
  rbc/heavydb.py
  rbc/remotejit.py
  rbc/tests/heavyai/test_heavyai.py
Labels: enhancement

#465 Introduce RBC_DEBUG env var
  doc/envvars.rst
  doc/index.rst
  rbc/remotejit.py
Labels: enhancement

#469 remove _make_udtf_old
  .github/workflows/label_check.yml
  rbc/heavydb.py
Labels: code quality

#460 Rename Bytes -> TextEncodingNone
  doc/api.rst
  rbc/heavyai/__init__.py
  rbc/heavyai/buffer.py
  rbc/heavyai/bytes.py
  rbc/heavyai/text_encoding_dict.py
  rbc/heavyai/text_encoding_none.py
  rbc/heavydb.py
  rbc/tests/__init__.py
  rbc/tests/heavyai/test_caller.py
  rbc/tests/heavyai/test_heavyai.py
  rbc/tests/heavyai/test_text.py
Labels: enhancement

#470 Fix issue #467 - Move imports to rbc.heavydb
  .github/workflows/rbc_test.yml
  rbc/heavydb.py
  rbc/heavydb_backend/__init__.py
  rbc/heavydb_backend/array.py
  rbc/heavydb_backend/buffer.py
  rbc/heavydb_backend/column.py
  rbc/heavydb_backend/column_list.py
  rbc/heavydb_backend/mathimpl.py
  rbc/heavydb_backend/metatype.py
  rbc/heavydb_backend/npyimpl.py
  rbc/heavydb_backend/pipeline.py
  rbc/heavydb_backend/python_operators.py
  rbc/heavydb_backend/table_function_manager.py
  rbc/heavydb_backend/text_encoding_dict.py
  rbc/heavydb_backend/text_encoding_none.py
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/stdlib/__init__.py
  rbc/stdlib/creation_functions.py
  rbc/stdlib/datatypes.py
  rbc/stdlib/elementwise_functions.py
  rbc/stdlib/statistical_functions.py
  rbc/tests/heavydb/__init__.py
  rbc/tests/heavydb/test_array.py
  rbc/tests/heavydb/test_array_api_unsupported.py
  rbc/tests/heavydb/test_array_functions.py
  rbc/tests/heavydb/test_array_math.py
  rbc/tests/heavydb/test_array_methods.py
  rbc/tests/heavydb/test_array_null.py
  rbc/tests/heavydb/test_array_operators.py
  rbc/tests/heavydb/test_black_scholes.py
  rbc/tests/heavydb/test_caller.py
  rbc/tests/heavydb/test_column_arguments.py
  rbc/tests/heavydb/test_column_basic.py
  rbc/tests/heavydb/test_column_default.py
  rbc/tests/heavydb/test_column_list.py
  rbc/tests/heavydb/test_column_null.py
  rbc/tests/heavydb/test_column_runtime_alloc.py
  rbc/tests/heavydb/test_constants.py
  rbc/tests/heavydb/test_device_selection.py
  rbc/tests/heavydb/test_external.py
  rbc/tests/heavydb/test_heavyai.py
  rbc/tests/heavydb/test_imports.py
  rbc/tests/heavydb/test_math.py
  rbc/tests/heavydb/test_mlpack.py
  rbc/tests/heavydb/test_template.py
  rbc/tests/heavydb/test_testing.py
  rbc/tests/heavydb/test_text.py
  rbc/tests/heavydb/test_text_encoding.py
  rbc/tests/heavydb/test_treelite.py
  rbc/tests/heavydb/test_udtf.py
Labels: code quality

#471 heavydb_ -> HEAVYDB_
  .github/workflows/rbc_test.yml
Labels: code quality, skip-tests

#474 Do not override user specified `dbname`
  rbc/heavydb.py
Labels: code quality

#477 Restore heavydb cmd to run tests on GitHub Actions
  .github/workflows/rbc_test.yml
Labels: tests
