Repository xnd-project/rbc, pull requests merged in 2022-07, with the labels that each got.

#503 Generate fields annotation
  rbc/heavydb/remoteheavydb.py
Labels: enhancement

#500 Update docs
  doc/api.rst
  rbc/heavydb/array.py
  rbc/heavydb/column.py
  rbc/heavydb/column_list.py
  rbc/heavydb/text_encoding_dict.py
  rbc/heavydb/text_encoding_none.py
  rbc/heavydb/timestamp.py
Labels: documentation

#506 Maintainance of rbc for heavydb 6.2
  .github/workflows/rbc_test.yml
  rbc/common.thrift
  rbc/extension_functions.thrift
  rbc/heavydb/remoteheavydb.py
  rbc/tests/heavydb/test_heavydb_thrift.py
  rbc/tests/heavydb/test_mlpack.py
  rbc/tests/heavydb/test_udtf.py
Labels: code quality

#499 Add support for string proxy methods
  rbc/__init__.py
  rbc/heavydb/__init__.py
  rbc/heavydb/array.py
  rbc/heavydb/buffer.py
  rbc/heavydb/column.py
  rbc/heavydb/column_list.py
  rbc/heavydb/remoteheavydb.py
  rbc/heavydb/string_dict_proxy.py
  rbc/heavydb/text_encoding_dict.py
  rbc/heavydb/text_encoding_none.py
  rbc/irtools.py
  rbc/libfuncs.py
  rbc/tests/heavydb/test_column_list.py
  rbc/tests/heavydb/test_text_encoding_dict.py
  rbc/tests/heavydb/test_text_encoding_none.py
  rbc/tests/test_typesystem.py
Labels: enhancement

#502 Numba 0.56
  .github/workflows/rbc_test.yml
  environment.yml
  rbc/externals/heavydb.py
  rbc/externals/stdio.py
  rbc/heavydb/buffer.py
  rbc/heavydb/column.py
  rbc/heavydb/table_function_manager.py
  rbc/irutils.py
  rbc/structure_type.py
  requirements.txt
Labels: enhancement

#504 Add enumerate(columnlist)
  rbc/heavydb/buffer.py
  rbc/heavydb/column_list.py
  rbc/tests/heavydb/test_column_list.py
Labels: enhancement
