Repository xnd-project/rbc, pull requests merged in 2022-02, with the labels that each got.

#425 MAINT: more information in message when raising when no runtime
  rbc/irtools.py
  rbc/omniscidb.py
Labels: enhancement, omniscidb

#424 Support remote calling of run-time UDF/UDTFs from Python
  .github/workflows/rbc_test.yml
  notebooks/rbc-intro.ipynb
  notebooks/rbc-simple.ipynb
  rbc/omnisci_backend/omnisci_bytes.py
  rbc/omnisci_backend/omnisci_column.py
  rbc/omnisci_backend/omnisci_text_encoding.py
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/tests/__init__.py
  rbc/tests/test_omnisci.py
  rbc/tests/test_omnisci_caller.py
  rbc/tests/test_remotejit.py
  rbc/tests/test_typesystem.py
  rbc/thrift/server.py
  rbc/typesystem.py
  rbc/utils.py
  test_requirements.txt
Labels: enhancement

#429 Warn if remove_features dictionary requires an update
  rbc/irtools.py
Labels: bug, enhancement

#426 ENH: add unregister of callers locally and on the server
  rbc/omniscidb.py
  rbc/tests/test_omnisci.py
  rbc/tests/test_omnisci_mlpack.py
Labels: enhancement, omniscidb

#433 Disable fast-fail for remotejit tests for CI stability, patch pythrift2 TServerSocket.close
  .github/workflows/rbc_test.yml
  rbc/thrift/server.py
Labels: bug

#440 Doc using pydata-sphinx-theme
  doc/conf.py
  test_requirements.txt
Labels: documentation

#435 add support for enumerate(Array, Column)
  .github/workflows/rbc_test.yml
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_column_basic.py
Labels: enhancement
