Repository xnd-project/rbc, pull requests merged in 2022-01, with the labels that each got.

#393 Maintainance of testing against omniscidb master
  rbc/errors.py
  rbc/extension_functions.thrift
  rbc/irtools.py
  rbc/omnisci_backend/omnisci_buffer.py
Labels: bug, omniscidb, tests

#392 Fix memory leaks when allocating buffers and arrays
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_pipeline.py
  rbc/rbclib/_rbclib.c
  rbc/tests/stdlib/test_array_api.py
Labels: bug, omniscidb

#398 Better error messages when cffi is missing
  rbc/rbclib/__init__.py
  setup.py
Labels: bug, code quality

#390 add numba 0.55 and omniscidb 5.9/5.10 from conda to CI
  .github/workflows/eval-notebooks.yml
  .github/workflows/rbc_test.yml
  README.md
Labels: enhancement

#405 Implement dtype attribute access and comparison
  rbc/omnisci_backend/omnisci_buffer.py
  rbc/omnisci_backend/omnisci_pipeline.py
  rbc/tests/test_omnisci_array.py
  rbc/tests/test_omnisci_array_functions.py
  rbc/tests/test_omnisci_column_basic.py
Labels: enhancement

#407 Fix `Caller.__repr__` for JIT without local
  rbc/remotejit.py
  rbc/targetinfo.py
Labels: bug, omniscidb

#403 ENH: forbid direct calls to `RemoteOmnisci`
  rbc/omniscidb.py
  rbc/remotejit.py
  rbc/tests/test_omnisci.py
Labels: bug, enhancement

#410 another attempt at release v0.7.0
  .github/workflows/pypi.yml
Labels: enhancement, Skip-Changelog

#412 Update release scripts
  .github/workflows/eval-notebooks.yml
  .github/workflows/pypi.yml
  .github/workflows/rbc_test.yml
Labels: enhancement, Skip-Changelog

#413 update action file to include missing require
  .github/workflows/pypi.yml
Labels: enhancement, Skip-Changelog

#414 push to test pypi
  .github/workflows/pypi.yml
  .github/workflows/rbc_test.yml
Labels: enhancement, Skip-Changelog, skip-tests

#415 Prep. release - Push to pypi
  .github/workflows/pypi.yml
Labels: enhancement, Skip-Changelog, skip-tests

#417 include _rbclib.h - prep for 0.7.1 release
  setup.py
Labels: enhancement, Skip-Changelog, skip-tests

#419 remove cffi from setup_requires and install it before building the wheel
  .github/workflows/pypi.yml
  setup.py
Labels: enhancement, skip-tests
