Repository xnd-project/rbc, pull requests merged in 2023-05, with the labels that each got.

#542 Revise device support
  rbc/external.py
  rbc/heavydb/day_time_interval.py
  rbc/heavydb/remoteheavydb.py
  rbc/heavydb/row_function_manager.py
  rbc/heavydb/string_dict_proxy.py
  rbc/heavydb/table_function_manager.py
  rbc/heavydb/timestamp.py
  rbc/heavydb/year_month_time_interval.py
  rbc/irtools.py
  rbc/remotejit.py
  rbc/targetinfo.py
  rbc/tests/heavydb/test_array.py
  rbc/tests/heavydb/test_array_methods.py
  rbc/tests/heavydb/test_array_operators.py
  rbc/tests/heavydb/test_black_scholes.py
  rbc/tests/heavydb/test_caller.py
  rbc/tests/heavydb/test_column_basic.py
  rbc/tests/heavydb/test_external.py
  rbc/tests/heavydb/test_nrt_string.py
  rbc/tests/heavydb/test_text_encoding_dict.py
  rbc/tests/heavydb/test_text_encoding_none.py
  rbc/tests/heavydb/test_udtf.py
  rbc/tests/test_remotejit.py
  rbc/utils.py
Labels: bug, enhancement, deprecation

#545 Fix readthedocs CI failure
  rbc/typesystem.py
  test_requirements.txt
Labels: bug, maintenance

#537 Implement Geo types
  .github/workflows/rbc_test.yml
  doc/api.rst
  rbc/heavydb/__init__.py
  rbc/heavydb/abstract_type.py
  rbc/heavydb/allocator.py
  rbc/heavydb/array.py
  rbc/heavydb/buffer.py
  rbc/heavydb/column.py
  rbc/heavydb/column_array.py
  rbc/heavydb/column_flatbuffer.py
  rbc/heavydb/column_geolinestring.py
  rbc/heavydb/column_geomultilinestring.py
  rbc/heavydb/column_geomultipoint.py
  rbc/heavydb/column_geomultipolygon.py
  rbc/heavydb/column_geopoint.py
  rbc/heavydb/column_geopolygon.py
  rbc/heavydb/column_list.py
  rbc/heavydb/day_time_interval.py
  rbc/heavydb/geo_nested_array.py
  rbc/heavydb/geolinestring.py
  rbc/heavydb/geomultilinestring.py
  rbc/heavydb/geomultipoint.py
  rbc/heavydb/geomultipolygon.py
  rbc/heavydb/geopoint.py
  rbc/heavydb/geopolygon.py
  rbc/heavydb/point2d.py
  rbc/heavydb/remoteheavydb.py
  rbc/heavydb/table_function_manager.py
  rbc/heavydb/text_encoding_dict.py
  rbc/heavydb/timestamp.py
  rbc/heavydb/year_month_time_interval.py
  rbc/libfuncs.py
  rbc/tests/__init__.py
  rbc/tests/heavydb/test_caller.py
  rbc/tests/heavydb/test_geo_basic.py
  rbc/tests/heavydb/test_geolinestring.py
  rbc/tests/heavydb/test_geomultipolygon.py
  rbc/tests/heavydb/test_geopoint.py
  rbc/tests/heavydb/test_geopolygon.py
  rbc/tests/heavydb/test_multilinestring.py
  rbc/tests/heavydb/test_testing.py
  rbc/typesystem.py
Labels: enhancement, heavydb

#546 Replace "builder.alloca" by "allocate_varlen_buffer"
  rbc/heavydb/buffer.py
  rbc/heavydb/text_encoding_none.py
Labels: bug

#551 Fix heavydb server (built with llvm 14) crash when using numba with llvm 11
  rbc/irtools.py
  rbc/tests/heavydb/test_math.py
Labels: bug, heavydb

#549 Use new external keyword arg
  rbc/heavydb/column_flatbuffer.py
  rbc/heavydb/geo_nested_array.py
  rbc/heavydb/table_function_manager.py
  rbc/tests/test_externals_cmath.py
Labels: enhancement

#554 Change release script to only recognize tags in the format of v*.*.*
  .github/workflows/pypi.yml
Labels: enhancement, skip-tests, maintenance

#556 Update release script
  .github/workflows/changelog.yml
  .github/workflows/pypi.yml
Labels: skip-tests, maintenance

#557 update tag-version.sh
  utils/tag-version.sh
Labels: skip-tests, maintenance

#558 Update release script to include changelog release step
  .github/workflows/pypi.yml
Labels: skip-tests, maintenance

#562 Fix eval-notebooks CI job
  .github/workflows/rbc_test.yml
Labels: Skip-Changelog, tests
