Repository xnd-project/rbc, pull requests merged in 2023-02, with the labels that each got.

#527 Add instructions to build and test RBC
  doc/api.rst
  doc/conf.py
  doc/developer.rst
  doc/index.rst
  rbc/heavydb/column_list_array.py
  test_requirements.txt
Labels: enhancement, documentation, skip-tests

#529 Introduce Opaque pointers
  .github/workflows/rbc_test.yml
  rbc/external.py
  rbc/heavydb/column.py
  rbc/heavydb/opaque_pointer.py
  rbc/heavydb/row_function_manager.py
  rbc/heavydb/string_dict_proxy.py
  rbc/heavydb/table_function_manager.py
  rbc/heavydb/text_encoding_none.py
  rbc/heavydb/utils.py
Labels: enhancement

#530 Fix a bug when clang compiler is not available.
  rbc/ctools.py
  rbc/heavydb/remoteheavydb.py
  rbc/irtools.py
Labels: bug, code quality
